name: Test Frontend Build

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Test Frontend Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test Frontend Build
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.4
      - run: yarn install && yarn build
